version: "3.8"

services:
  db:
    image: postgres:17
    container_name: wedding_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: wedding_backend
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

volumes:
  pgdata:
